#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc delay.sv 
verilator -Wall --cc lfsr.sv 
verilator -Wall --cc f1_fsm.sv
verilator -Wall --cc clktick.sv
verilator -Wall --cc --trace lights_out.sv --exe lo_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vlights_out.mk Vlights_out

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vlights_out
echo "\nSimulation completed"
