#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f lfsr.vcd

# run Verilator to translate Verlig into C++, including C++ testbench
verilator -Wall --trace --cc lfsr.sv --exe lfsr_tb.cpp

# build C++ project via make file automatically generated by Verilator
make -j -C obj_dir/ -f Vlfsr.mk Vlfsr

# run the executable simulation file
obj_dir/Vlfsr